version: '3.10.5'
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/project
    working_dir: /usr/src/project/backend/app
    command: /bin/sh -c 'alembic upgrade head && poetry run python -m app'
    networks:
      - app-network
    ports:
      - "8080:8080"
    env_file:
      - ./backend/app/.env
    depends_on:
      - db
      - celery-beat
      - celery
      - flower
  db:
    image: postgres:14.0-alpine
    container_name: postgres
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/app/.env
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:3.10.6
    restart: always
    container_name: rabbitmq_broker
    volumes:
      - ./:/usr/src/project
    working_dir: /usr/src/project/backend/app
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build: .
    restart: always
    container_name: celery_worker
    volumes:
      - ./:/usr/src/project
    working_dir: /usr/src/project/backend/app
    command: celery -A app.services.worker.celery_app worker -l info
    networks:
      - app-network
    depends_on:
        - rabbitmq

  celery-beat:
    build: .
    restart: always
    container_name: celery_beat
    volumes:
      - ./:/usr/src/project
    working_dir: /usr/src/project/backend/app
    command: celery -A app.services.worker.celery_app beat -l info
    networks:
      - app-network
    depends_on:
      - rabbitmq

  flower:
    build: .
    restart: always
    container_name: flower
    volumes:
      - ./:/usr/src/project
    working_dir: /usr/src/project/backend/app
    command: bash -c "celery -A app.services.worker.celery_app flower  --address=0.0.0.0 --port=5566 && 
      celery -A app.services.worker.celery_app flower --broker=amqp://rabbitmq:5672"
    networks:
      - app-network
    ports:
      - '5566:5566'
    depends_on:
      - celery
      - celery-beat
      - rabbitmq

volumes:
  postgres_data:

networks:
  app-network:

