version: '3.10'
services:
  web:
    build: .
    working_dir: /usr/src/project/backend/app
    command: /bin/sh -c 'alembic upgrade head && python -m app'
    networks:
      - app-network  
    ports:
      - 8000:8080
    env_file:
      - ./backend/app/.env
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network  
    env_file:
      - ".env"
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  rabbitmq-broker:
      image: rabbitmq:3-management-alpine
      ports:
        - "4369:4369"
        - "5672:5672"
        - "25672:25672"
        - "15672:15672"
  celery-beat:
    build: .
    command: celery -A celery_app beat -l info
    working_dir: /usr/src/project/backend/app/app/services/worker
    depends_on:
      - rabbitmq-broker
      - web
  dashboard:
      build: .
      working_dir: /usr/src/project/backend/app/app/services/worker
      command: >
        bash -c "celery -A celery_app flower --port=5566 && 
        celery -A celery_app flower  --address=0.0.0.0 --port=5566 && 
        celery -A celery_app flower --broker=amqp://guest:guest@rabbitmq:5672//"
      ports:
        - "5566:5566"
      depends_on:
        - web
        - db
        - rabbitmq-broker
        - celery-beat
volumes:
  postgres_data:

networks:
  app-network:

