version: '3.10'
services:
  web:
    build: .
    working_dir: /usr/src/project/backend/app
    command: /bin/sh -c 'alembic upgrade head && python -m app'
    networks:
      - app-network
    ports:
      - 8000:8080
    env_file:
      - ./backend/app/.env
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network
    env_file:
      - ".env"
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:3.10.6
    restart: always
    container_name: vcd_api_service_rabbitmq

  celery:
    build: .
    restart: always
    container_name: vcd_api_service_celery
    command: celery -A backend.app.app.services.worker.celery_app worker -l INFO
    depends_on:
        - rabbitmq

  celery-beat:
    build: .
    restart: always
    container_name: vcd_api_service_celery_beat
    command: celery -A backend.app.app.services.worker.celery_app beat -l INFO
    depends_on:
      - rabbitmq

  flower:
    build: .
    restart: always
    container_name: vcd_api_service_flower
    command: celery -A backend.app.app.services.worker.celery_app flower --port=5556 --url_prefix=flower -l INFO
    depends_on:
      - celery
      - celery-beat

volumes:
  postgres_data:

networks:
  app-network:

